# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iyara_booking-app' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iyara_booking-app
pod 'Firebase/Analytics'
pod 'FSCalendar', :git=> 'https://github.com/WenchaoD/FSCalendar'
pod 'MessageKit'
pod 'MessageInputBar' 

  target 'iyara_booking-appTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iyara_booking-appUITests' do
    # Pods for testing
  end

end
